Tb 20231810 assignment1
BG-Tia/AssignmentsBrightGen pull request #2
Opened 2023-10-18 14:21 UTC by BG-Tia

I would like to add this to main.

2023-10-18 16:12 UTC, UKJWL requested changes
Overall really solid first go at it. I like that you've thought about the context in which things are used, like creating an app. 

Descriptions are great, really clear to understand what the purpose is. 

The model itself has a bit of an issue, it's not major and it's probably a hurdle that most if not all the graduates don't spot first time. I know I didn't anyway. 

Here's some clues as to what you may be missing:

- You might want to think about how the relationships work in your implementation in some more _**detail**_.  Do the relationships you've chosen fit the purpose of the requirements? Have a look into the Salesforce relationship properties if you're unsure.
- 
- You've also got something in here that does serve the purpose as intended but it's merged together. Have another read of the requirements and let me know what you think it could be.

Overall really good start, nice one.

2023-10-18 16:12 UTC, UKJWL commented on force-app/main/default/objects/Task__c/fields/Journey_del__c.field-meta.xml
> +    <type>Lookup</type>
You're correct in assuming there is a relationship between the two objects. What happens when the related journey is deleted?

2023-10-18 16:12 UTC, UKJWL commented on force-app/main/default/objects/Task__c/fields/Journey_del__c.field-meta.xml
Does it make sense for a task to share both a template and a journey?

2023-10-26 10:43 UTC, BG-Tia commented on force-app/main/default/objects/Template__c/fields/Task__c.field-meta.xml
Changed this~ template tasks no longer deleted on journey task deletion.

2023-10-26 10:43 UTC, BG-Tia commented on force-app/main/default/objects/Task__c/fields/Journey_del__c.field-meta.xml
Realised error here! Changed through task object and created 'Template Task' ~ a separate task object to make template tasks independent from journey.

2023-10-26 14:11 UTC, UKJWL commented on force-app/main/default/objects/Task__c/Task__c.object-meta.xml
Delete this pleas.

2023-10-26 14:12 UTC, UKJWL commented on force-app/main/default/layouts/Task__c-Task Layout.layout-meta.xml
Delete this please if it doesn't automatically after you delete the object.

2023-10-30 14:07 UTC, merged